name: "Hello world workflows"

#Controls when the action will run. Triggers the workflow on push done to main or production branch
on:
  push:
    branches:
      - main
      - production

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "hello world"

      - name: "Print current date"
        run: date