name: "Multi event pipeline / workflows" # Name of the pipeline

on: 
    push: #Event: whenever a push is made to the repository on the main / test branch
        branches:
            - main
            - test
    pull_request: # Event: Whenever a pull resquest is made to the repository
            branches:
                - main
    workflow_dispatch: 

jobs: 
    on-push: # Name of job, job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest # Define the environmnet of runner on which job runs
        steps: # Steps to be executed int the job
            - name: "Runing on main/test push" # step 1
              run: echo "Runing on main/test push"
    
    on-pull-request: # New job ,job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest # Define the environmnet of runner on which job runs
        steps: # Steps to be executed int the job
            - name: "Runing on main/test push" # step 1
              run: echo "Runing on main/test push"

    on-workflow-dispatch: #job 3
        if: github.event_name == 'workflow-dispatch'
        runs-on: ubuntu-latest # Define the environmnet of runner on which job runs
        steps: # Steps to be executed int the job
            - name: "Runing on workflow dispatch" # step 1
              run: echo "Runing on workflow dispatch"
